<!-- Početak izbornik -->
<!-- <div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('nazivAPP'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text show-for-large">
            <?php #echo APP::config('nazivAPP'); ?>
            </li>
            <li><a href="/">Početna</a></li>
            <li><a href="/">Forum</a></li>
            
                
                <?php #if(isset($_SESSION['korisnik']) && $_SESSION['korisnik']->uloga==='3'):?>
                    <li><a href="/operater/index">Operateri</a></li>
                <?php #else:?>
                    <li><a href="/nadzornaploca/profil">Profil</a></li>
                <?php # endif;?>
            
            <li><a href="/index/onama">O nama</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li>
            <?php #if(!isset($_SESSION['korisnik'])): ?>
                <a href="/index/prijava">Prijava</a>
            <?php #else:?>
                <a href="/index/odjava">Odjavi 
                <?php #echo $_SESSION['korisnik']->korisnickoIme; ?></a>
            <?php #endif;?>
            </li>
        </ul>
    </div>
</div> -->
<!-- Kraj izbornik -->
<div class="grid-container">
    
      <header class="row small-12 large-12">
        <div class="row top-bar small-12 large-12 data-topbar">
          <div class="columns top-bar-left small-3 large-5 ">
            <a href="index.php"><h3><?php echo APP::config('nazivAPP'); ?></h3></a> 
          </div>
          <div class="columns top-bar-right small-9 large-8 ">
            <ul class="menu align-right">
              <li><a href="index.php"> Naslovna </a></li>
              <li><a href="forumStart.php"> Forum </a></li>
              <li><a href="/index/onama">O nama</a></li>
              
              <?php if(isset($_SESSION['korisnik']) && $_SESSION['korisnik']->uloga==='3'):?>
                    <li><a href="/operater/index">Operateri</a></li>
                <?php #else:?>
                    <li><a href="/nadzornaploca/profil">Profil</a></li>
                <?php endif;?>
            
            
            </ul>
          </div>
          <div class="top-bar-right">
        <ul class="menu">
            <li>
            <?php if(!isset($_SESSION['korisnik'])): ?>
                <li><a href="loginForm.php">Registiraj se </a></li>
                <a href="/index/prijava">Prijava</a>
            <?php else:?>
                <a href="/index/odjava">Odjavi 
                <?php echo $_SESSION['korisnik']->korisnickoIme; ?></a>
            <?php endif;?>
            </li>
        </ul>
    </div>
        </div> <!-- End Top bar  -->
       