Iz pocetna.phtml <br />
<div id="main-content-section" class="row small-12 large-12">
        <pre class="column contentNaslovna"><span>                                                   Ideja i cilj ovog foruma je da 
                                        iz međusobnog djeljenja znanja, primjera,
                                  iskustva i saznanja, služi kao izvor informacija 
                          "živim ljudima" koji muku muče u interakciji
                  s pravnim sistemom, te da zajednički rješavamo nejasnoće, 
              pronalazimo rješenja i olakšamo si put u donošenju
   zaključaka i odluka o/u daljnjim načinima
            vlastitog djelovanja obrane 
                slobode i svog bića.
                
                                                Dobrodošli!
        </span></pre>  
