<form class="log-in-form" method="POST"
action="/index/autorizacija">
 <label>Korisnicko ime
    <input type="text" id="korisnickoIme" name="korisnickoIme" value="<?php echo $korisnickoIme ?>">
  </label>
  <label>Password
    <input type="password" id="lozinka" name="lozinka">
  </label>
  <p><input type="submit" class="button expanded" value="Log in"></input></p>
</form>
<?php echo $poruka;
password_verify($_POST['lozinka'],$rezultat->lozinka); ?>